Description of mptable.rs module
codenet/understanding-rust-vmm pull request #19
Opened 2022-09-12 11:08 UTC by priyanshs

2022-09-12 11:15 UTC, tmibvishal approved these changes

2022-09-12 11:16 UTC, tmibvishal requested changes

2022-09-12 11:16 UTC, tmibvishal commented on mptable.md
> +# [mptable](mptable.rs)
Testing 2

2022-09-15 12:50 UTC, ArkaMandal2001 reviewed
Testing

2022-09-15 12:50 UTC, ArkaMandal2001 commented on mptable.md
> +
Testing

2022-09-15 17:34 UTC, amar512-prog commented on mptable.md
> +## Introduction
Testing

2022-09-16 17:37 UTC, Laxman824 commented on mptable.md
> +
Testing

2022-09-17 13:14 UTC, SwarajGawande commented on mptable.md
> +
Testing

2022-09-17 17:11 UTC, jayantmishra99 commented on mptable.md
> +> The MP configuration table contains explicit configuration information about APICs, processors, buses, and interrupts. The table consists of a header, followed by a number of entries of various typ
Testing

2022-09-17 17:11 UTC, jayantmishra99 reviewed
reviewed

2022-09-20 09:59 UTC, codenet approved these changes
Very nice

2022-09-20 09:59 UTC, codenet commented on mptable.md
> +`cpu_num` allows the configuring of the number of vCPUs. `irq_num` refers to the number of intrurpt requests allowed within the configuration.
the configuring -> configuring
intrurpt -> interrupt

2022-09-20 09:59 UTC, codenet commented on mptable.md
> +A memory object is further initialised with the relevant parameters. A `MpfIntel` object is defined using prefefined values for `signature`, `length` and `specification`. Checksum for this allocation
prefefined

2022-09-20 09:59 UTC, codenet commented on mptable.md
> +Base pointer for the table is now set where all the specification of the virtualised resources shall be saved. Each of the vCPUs when stored in the table are allocated with the following data as per
~~the~~ written

2022-09-20 09:59 UTC, codenet commented on mptable.md
> +The are defined as follows
These

2024-06-24 18:12 UTC, closed without merging