Created vmm-reference-msrs.md
codenet/understanding-rust-vmm pull request #8
Opened 2022-09-12 10:11 UTC by ArkaMandal2001

Described working of msrs.rs

2022-09-12 10:15 UTC, ArkaMandal2001 commented
https://github.com/codenet/understanding-rust-vmm/pull/8

2022-09-15 05:36 UTC, kshitij86 commented on vmm-reference-msrs.md
> +Here is a brief description of how msrs.rs works from "vmm-reference/src/vm-vcpu-ref/src/x86_64/msrs.rs"
Testing

2022-09-16 13:38 UTC, Laxman824 reviewed
Testing

2022-09-16 13:38 UTC, Laxman824 commented on vmm-reference-msrs.md
> +
Testing

2022-09-17 06:31 UTC, CoderPanda1729 commented on vmm-reference-msrs.md
> +struct MsrRange {
Testing

2022-09-17 13:57 UTC, priyanshs reviewed
testing

2022-09-17 17:09 UTC, kshitij86 approved these changes

2022-09-20 07:53 UTC, codenet requested changes
Not a great PR. It doesn't go deep into what are MSRs, why are they used, how are they used in overall KVM functioning etc.

2022-09-20 07:53 UTC, codenet commented on vmm-reference-msrs.md
> +MSRS is used to store a half done process' state and continue with some other process and then come back to it, restore it and continue wth the work.
wth -> with

2022-09-20 07:53 UTC, codenet commented on vmm-reference-msrs.md
> +MSRS is used to store a half done process' state and continue with some other process and then come back to it, restore it and continue wth the work.
Unclear description. I don't get what MSRS is by reading this description.

2022-09-20 08:31 UTC, codenet commented
This PR describes the same topics as https://github.com/codenet/understanding-rust-vmm/pull/12/files Please directly add changes that you think are unique in your PR to the other PR.

2022-09-20 08:31 UTC, closed without merging